version: '3.1'

services:
    # login-server:
    #     image: valhalla/server
    #     build:
    #         context: ./
    #         dockerfile: Dockerfile
    #     command: -type=login
    #     ports:
    #         - 8484:8484
    #     restart: unless-stopped

    # channel-server:
    #     image: valhalla/server
    #     command: -type=channel
    #     volumes:
    #         - ./Data.nx:/app/wizetData
    #         - ./scripts/:/app/scripts/
    #     environment:
    #         - DB_USER=root
    #         - DB_PASSWORD=password
    #         - DB_DATABASE=maplestory
    #         - DB_ADDRESS=db
    #         - DB_PORT=3306
    #     ports:
    #         - 8686:8686
    #     restart: unless-stopped
        
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=maplestory
        restart: unless-stopped

    adminer:
        image: adminer
        ports:
            - 8080:8080
        restart: unless-stopped

    # elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    #     container_name: elasticsearch
    #     volumes:
    #         - esdata:/usr/share/elasticsearch/data
    #     ports:
    #         - 9200:9200
    #     restart: always
    
    # grafana:
    #     image: grafana/grafana
    #     ports:
    #         - "3000:3000"   

volumes:
    db-data:
    esdata: