version: '3.1'

services:
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=maplestory
        restart: unless-stopped

    adminer:
        image: adminer
        ports:
            - 8080:8080
        restart: unless-stopped

    # elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    #     container_name: elasticsearch
    #     volumes:
    #         - esdata:/usr/share/elasticsearch/data
    #     ports:
    #         - 9200:9200
    #     restart: always
    
    # grafana:
    #     image: grafana/grafana
    #     ports:
    #         - "3000:3000"   

volumes:
    db-data:
    esdata: